#!/usr/bin/env bash

xrandr=$(xrandr)

con_monitors=$(echo $xrandr | grep -c " connected ")

# xrandr --output DP1 --mode 2560x1440 --right-of eDP1

xrandr --output eDP1 --auto
xrandr --output DP1 --mode 1920x1080 --left-of eDP1

# Full 4k resolution
# xrandr --output DP1 --auto --right-of eDP1

[ -f ~/.fehbg ] && ~/.fehbg
